spotify:
  outputs:
    dev:
      dataset: spotify
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../credentials/gcp.json
      location: US
      method: service-account
      priority: interactive
      project: XXXXXXXXXXXXXXXXX
      threads: 1
      type: bigquery
  target: dev
