# Spin up terraform service
docker-compose up --build -d
# init
docker run --rm terraform init
# plan
docker run --rm terraform plan
# apply
docker run --rm terraform apply
# destroy (when needed)
docker run --rm terraform destroy